name: tracker
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  geolocator: ^5.3.1
  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.7
  flutter_signin_button: ^1.0.0
  flutter_facebook_login: ^3.0.0
  google_maps_flutter: ^0.5.21+15
  location: ^2.3.5
  shared_preferences: ^0.5.7+3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.10
  equatable: ^1.2.0
  #flutter_bloc: ^4.0.1
  flutter_bloc: ^2.0.0
  meta: ^1.1.6
  device_info: ^0.4.2+4
  email_validator: ^1.0.4
dependency_overrides:
  path: 1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.0


flutter_icons:
  image_path_android: "assets/images/ct_logo.png"
  image_path_ios: "assets/images/ct_logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"


flutter:

  uses-material-design: true
  assets:
    - assets/images/icpep.png
    - assets/images/direction.png
    - assets/images/ct_logo.png
